- name: New Relic Application Deployment Marker
  uses: newrelic/deployment-marker-action@v2.4.0
  with:
    apiKey: ${{ secrets.NEW_RELIC_API_KEY }}
    guid: ${{ secrets.NEW_RELIC_DEPLOYMENT_ENTITY_GUID }}
    version: ${{ env.RELEASE_VERSION }}
    # The geographical region for your New Relic account - US or EU. Default: US
